
export const CHANGE_SHOWBAR = "CHANGE_SHOWBAR";
export const CHANGE_MEBINFO = "CHANGE_MEBINFO";
export const CHANGE_TELNO = "CHANGE_TELNO";
export const CHANGE_NICKNAME = "CHANGE_NICKNAME";
export const CHANGE_AVATARICONURL = "CHANGE_AVATARICONURL";
export const ADD_BANNERIMG = "ADD_BANNERIMG";
export const CHANGE_LOCATION = "CHANGE_LOCATION";
export const CHANGE_AIMLOCATION = "CHANGE_AIMLOCATION";
